language: scala
jdk: oraclejdk8
scala: 2.12.8

jobs:
  include:
    - stage: test
      script: sbt scalafmtCheck scalafmtSbtCheck
      name: "Formatting check"
    - script: sbt test scripted
      name: "Tests run"
    - stage: publish
      script: sbt ^publish

stages:
  - name: test # runs on master commits and PRs
    if: NOT tag =~ ^v
  - name: publish # runs on main repo master commits or version-tagged commits
    if: repo = lightbend/sbt-publish-rsync AND ( ( branch = master AND type = push ) OR tag =~ ^v )

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

before_cache:
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete

notifications:
  email:
    on_success: never

env:
  global:
    # travis encrypt BINTRAY_USER=...
    - secure: "GCZ1uv7QCEj7k0VQdUjmspYvX/g7HMRX/3UBSu/84Mfi4TpcFH+FkgitUHmJnwnpbr+4afxAd1EO7ZkS7UqnZyyZxw2KerjAVl7S+Kg8grqmOB4cxmo83aztaVoEC4jmiR+1pymhVyuNJDb3QadRg4DAygCRaGFbG5H6cBh413aQLkpHGDqH7K+Ereoho5xwzgshbJdInafclSnBfyTCTFq6IOFfbgdVgzY6coXD/yfb6F97JTqlJftNF2N00dkQvvyYNnEDl4JNJLKLTpsIFT1GgSwzVIOce7JFSGLzC6z5E/fE/yksUAn1hdhUZ48gWoY8XE27drd3cXr7enteroFGJHyqxLAFCdvIfaFoMpZG0oDZlboBw0aXDVDFdpWz6hbbJ+2BTfwWL7BsuqcUEQdxnXDE4elYeDRXWsbtpdmNkwy3BWrau1H81832ZZvWBEIjCMoqOXv6qdvcy2O7wQSnNJ2avr3+dT4h3UEmIHbEpLIX4BfEPyvLSaiVP1aRcXnpB6e7TedXYWpklu9eDvyXcHxgLQCykP+acuxDyF3qGdJjwhhn3KhfEVPB8mdm0VdqvxAQFhgJGl8CR6A5LilNaAgHituayauG91dl2FmB2JfNRA22Oxcwktel6pcA3l4RB1za8UII7WfUtcU1zLSFo3O3lIzgPbkx0zlWVnY="
    # travis encrypt BINTRAY_PASS=...
    - secure: "IqRqXkokc3juUZH7++/NYUUgT2gr5uYw7QmM8+QY9jAWafA2hNY825ODgZn/zzdXV3/7QGW+0bpUBNlkLX3H2ist1XXLKkac1ORoNDbdupiCJx101J9cxzSb3iZiBKs9XAKcK3VBXTvYtg2TM7gCR3c9K7WXjpZZXQbqe9qYYNuUfm4pn2IkH6z1uf5qthACMwFTOrwFqimMEkt4cywyMJ0PQlhEweDS9QSoxXlv9jw1quAjMInTRbZ+2EEQXKlWjUg3acXUepu/dmjgiiC5ufDOF35zJaaD8QypMpQzX2kBD0iRbg4HMZemcwfjZsZcfH4BV+taCxRR8TtKzZ7x6sCT4Zy/RDnfDYK53cfm0u0NQ3GsbDsW/NBQJDd3MGbTapjqHpsDId7nQBwil6GfxgPT9Zvf4R2xqGBBjcKIsxbgHJ1FLk4XyjWHRl+HQ6noYvdy/e/bqG7mTwOLFhZyv2KQR2/ys4NtI/2kzf0cwuQnvrTUkOktMvPNj08/8d/fSt85rgaKMUJzPylVLy/THMpJktKB09APDUbNmpz4g2MTXl8w27Hxf4u/17wy09hoVNtqDH0QpoSG2d4/dCESwxJ7InuVGdwHNA/K+hwVC1IiC6JU8h1Qw8X9bz9iPza2ogDp/2QzZLvUDXV2Fr0FL0QkIRzH39YRX99guyDbmMQ="
