name: Validate and test

on:
  pull_request:
  push:
    branches:
      - main
    tags-ignore: [ v.* ]

permissions:
  contents: read

jobs:
  check-code-style:
    name: Checks
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0
        with:
          # we don't know what commit the last tag was it's safer to get entire repo so previousStableVersion resolves
          fetch-depth: 0

      - name: Checkout GitHub merge
        if: github.event.pull_request
        run: |-
          git fetch origin pull/${{ github.event.pull_request.number }}/merge:scratch
          git checkout scratch

      - name: Cache Coursier cache
        uses: coursier/cache-action@v6.4.0

      - name: Set up JDK 11
        uses: coursier/setup-action@v1.3.0
        with:
          jvm: temurin:1.11.0

      - name: Code style check, compilation and scripted test
        run: |-
          sbt scalafmtCheckAll scalafmtSbtCheck headerCheck scripted